- name: Check if monitoring server is already installed
  stat: path=/home/{{ user }}/monitoring-server/node_modules
  register: check_server_path

- name: Is the monitoring server already installed?
  debug: msg="Yes, it is! Monitoring server installation will be skipped this time."
  when: check_server_path.stat.exists == true

- name: Clones the monitoring-server repository
  git:
    repo=https://github.com/excess-project/monitoring-server.git
    dest=/home/{{ user }}/monitoring-server
    force=yes
    version=release/16.6.1
  become: no
  when: check_server_path.stat.exists == false

- name: Install monitoring server
  npm: path=/home/{{ user }}/monitoring-server
  # issue with jade dependencies -> renaming to pug failed
  ignore_errors: yes
  when: check_server_path.stat.exists == false

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: Start the monitoring server using forever
  command: forever start /home/{{ user }}/monitoring-server/bin/www
  when: "forever_list.stdout.find('/home/{{ user }}/monitoring-server/bin/www') == -1"

- name: Wait for the monitoring server to start
  wait_for:
    port=3030
    delay=5
