- name: Check if curl is already installed
  stat: path={{ ROOT }}/bin/curl/bin/curl
  register: check_curl_path

- name: Is curl already installed?
  debug: msg="Yes, it is! Curl installation will be skipped this time."
  when: check_curl_path.stat.exists == true

- name: Download CURL
  get_url: url={{ CURL_URL }} dest="{{ ROOT }}/{{ CURL }}-{{ CURL_VERSION }}.tar.gz" validate_certs=no timeout=30
  when: check_curl_path.stat.exists == false

- name: Unarchive CURL
  unarchive: src="{{ ROOT }}/{{ CURL }}-{{ CURL_VERSION }}.tar.gz" dest={{ ROOT }} copy=no
  when: check_curl_path.stat.exists == false

- name: Build curl
  shell: 'cd {{ COMPILE_PATH_CURL }};{{ item }}'
  with_items:
    - './configure --prefix={{ INSTALL_PATH_CURL }}'
    - make all
    - make install
  when: check_curl_path.stat.exists == false