- name: Check if NVIDIA GDK binaries are already installed
  stat: path={{ ROOT }}/bin/nvidia/usr/bin/nvidia-healthmon
  register: check_nvidia_path

- name: Is NVIDIA GDK already installed?
  debug: msg="Yes, it is! NVIDIA GDK installation will be skipped this time."
  when: check_nvidia_path.stat.exists == true

- name: Download NVIDIA GDK
  get_url: url={{ NVIDIA_URL }} dest="{{ ROOT }}/{{ NVIDIA }}_{{ NVIDIA_VERSION }}.run" validate_certs=no timeout=30
  when: check_nvidia_path.stat.exists == false

- name: Build NVIDIA GDK
  shell: 'cd {{ ROOT }};{{ item }}'
  with_items:
    - 'chmod +x {{ NVIDIA }}_{{ NVIDIA_VERSION }}.run'
    - './{{ NVIDIA }}_{{ NVIDIA_VERSION }}.run --silent --installdir={{ INSTALL_PATH_NVIDIA }}'
  ignore_errors: yes
  when: check_nvidia_path.stat.exists == false